### PR TITLE
Closes #2. Added a method to validate user credentials

### LINKED ISSUE #2: Provide a way to not create a token after a successful login
At the moment, as soon as we login I create a new authorization (so, a new Personal Access Token). Maybe people don't always want that. Provide a way for them to login without in.

I think I'm in favor of different constructors instead of one constructors with lots of inputs. The current one can be DWIM, but other restrictive ones can do only exactly what they are told to do.

### PR DESCRIPTION
**Pull request by amarnus**
- Included check for Github accounts protected by 2fa.

**Usage:**

``` perl
my $ghojo = Ghojo->new;
#-- Login first
$ghojo->login( {
    username => 'foo',
    password => 'bar',
} );
#-- Authorize Later
$ghojo->create_authorization;
```

### CODE REVIEW

**Comment by amarnus** [comment]
I'm sorry that I had to open & close this pull request multiple times - had to do it just to do a rebuild on Travis. The tests have been behaving weirdly - they passed once and failed thrice. 

For my latest commit, the tests passed from my own repo: https://travis-ci.org/amarnus/ghojo/builds/165586638 - so I doubt if their failing here has anything to do with the code change(s).

Anyway, would love to hear your thoughts, Brian.

**Comment by briandfoy** [comment]
I think there's a start here, but we need to figure out these Travis failures.

**Comment by amarnus** [comment]
Tests passed!

I wonder if the issue could be that as Github only allows 60 unauthenticated requests/hour and there could be multiple requests to their API from different projects coming from the Travis servers and they tie unauthenticated rate limits to the source IP, we are seeing these random test failures?

**Comment by briandfoy** [comment]
This looks good, but give me some time to think about this because I've been doing some surgery on my end too. Thanks!

**Comment by amarnus** [comment]
Sure, no problem!

**Comment by briandfoy** [comment]
I merged these by hand. Your specific commit SHAs don't show up in the log, but your changes (with you as the author) are there.

**Comment by amarnus** [comment]
Thanks, Brian! I see that you have attributed the commit.

**Pull request closed without merging**
